# SimpleDeathFinder – gives a Recovery Compass on respawn and removes it
# when the player reaches the death location.

give-on-respawn: true          # give one on respawn (optional)

remove-on-approach:
  enabled: true
  radius: 6.0                 # blocks
  check-interval-ticks: 20    # 20 = 1 second

# Keep older compasses tagged by this plugin when giving a new one
# (must be false so you can keep multiple active targets)
remove-old-compasses: false

messages:
  # Item messages
  given: "&aReceived recovery compass. It points to your last death."
  arrived: "&7You reached your death location. The compass crumbles."
  full-inventory: "&eInventory full – the compass was dropped in front of you."
  other-dimension: "&eYour death location is in another dimension – the compass spins."

  # ActionBar status (shown only while holding a tagged Recovery Compass)
  # placeholders: {dist},{x},{y},{z},{dim},{owner}
  path-status: "&bTarget:&f {dist}m &7(&f{dim} @ {x},{y},{z}&7)"
  path-different-world: "&eTarget is in another dimension – no distance."
  path-no-target: "&eNo death target available."

item:
  name: "&bRecovery Compass"
  lore:
    - "&7Points to your last death."
    - "&7Where: &f{dim} &7@ &f{x}&7,&f{y}&7,&f{z}"
    - "&7Owner: &f{owner}"

sound:
  arrived: "entity.experience_orb.pickup"   # any valid Bukkit sound
