name: SimpleDeathFinder
main: dev.yourserver.simpledeathfinder.SimpleDeathFinderPlugin
version: 1.0.0
api-version: '1.20'
author: yourserver
commands:
  sdf:
    description: SimpleDeathFinder commands
    usage: /sdf [reload|give <player>]
    permission: simpledeathfinder.use
permissions:
  simpledeathfinder.use:
    default: true
  simpledeathfinder.reload:
    default: op
  simpledeathfinder.give:
    default: op

