name: SimpleDeathFinder
main: dev.yourserver.simpledeathfinder.SimpleDeathFinderPlugin
version: ${project.version}
api-version: '1.20'
author: yourserver

commands:
  sdf:
    description: SimpleDeathFinder commands
    usage: /sdf [reload|give <player>]
    permission: simpledeathfinder.use
  deathpath:
    description: Toggle/Mode der Todespfad-Visualisierung
    usage: /deathpath [on|off|mode <foot|boat>|status]
    permission: simpledeathfinder.path

permissions:
  simpledeathfinder.use:
    default: true
  simpledeathfinder.reload:
    default: op
  simpledeathfinder.give:
    default: op
  simpledeathfinder.path:
    default: true
